- CHANGES.rst
- setup.cfg
- setup.py
* Switches the setup.py to use setuptools.
* Automatically installs ``ordereddict`` on Python < 2.7.
* Adds extras which can be used to install optional dependencies like ``pip install html5lib[genshi,datrie]``. The ``lxml`` extra is conditional on CPython.
* Adds an ``all`` extra which will install all optional dependencies which correctly handles lxml on non CPython interpreters.
* Marks wheels as universal.
Fixes #165 
Fixes #179
> Move Dependency Into setup.py and Make Universal Wheel

- html5lib/inputstream.py
- html5lib/tests/test_stream.py
This gets stuff working with `urllib.response.addurlinfo`. See #127 and #136.
> Add a more general fix for #127 (CPy #20007) based on #136.

- html5lib/filters/lint.py
- html5lib/tests/test_treewalkers.py
- html5lib/treewalkers/_base.py
- html5lib/treewalkers/genshistream.py
- html5lib/treewalkers/lxmletree.py
This makes the lint filter actually ensure tree walker implementations follow their supposed API, runs all of the tree walker tests through the filter, and fixes a number of bugs it shows up.
> Lint fixes

- setup.py
Otherwise setup.py fail with `error in html5lib setup command: Invalid environment marker: python_implementation == 'CPython'`
> Fix python implementation marker for setuptools 2.20

- setup.py
See <https://github.com/pypa/packaging/issues/72#issuecomment-213826903> for a discussion of the various setuptools different aliases support. This means we don't work with 20.2 to 20.6 (released mid-Feb till late-Mar 2016).
> Use the platform.python_implementation because it's the most compat

- html5lib/html5parser.py
- html5lib/inputstream.py
- html5lib/tests/test_encoding.py
As far as I can tell, this has never worked. o_O
> Get encoding reparsing actually working

- CHANGES.rst
- html5lib/treewalkers/lxmletree.py
#247, hopefully not hitting GitHub bugs…
> lxml ascii change

- CHANGES.rst
- html5lib/filters/lint.py
- html5lib/serializer/htmlserializer.py
- html5lib/tests/serializer-testdata/core.test
- html5lib/tests/serializer-testdata/injectmeta.test
- html5lib/tests/serializer-testdata/optionaltags.test
- html5lib/tests/serializer-testdata/options.test
- html5lib/tests/serializer-testdata/whitespace.test
- html5lib/tests/support.py
- html5lib/tests/test_serializer.py
#11 given this isn't picked up from the title
> Fix #11 by escaping enough to be safe in legacy browsers

- CHANGES.rst
- README.rst
- debug-info.py
- html5lib/inputstream.py
- html5lib/tests/test_encoding.py
- requirements-optional.txt
- setup.py
Replaces #219, splitting it up. It also gets rid of replacing the `ast` parsing of `__init__.py`, but I think we're unlikely to land that.
> Drop charade, cleanup setup.py

- CHANGES.rst
- README.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- html5lib/tests/test_treewalkers.py
> Fix #132: add test for #115, single character fragments

- requirements-install.sh
- requirements.txt
- setup.py
This tries to address #231 again, reverting to platform_python_implementation. This should work everywhere with setuptools 18.5 above; see #231 for more discussion of this.
> Try dealing with the backwards incompatible changes in setuptools again

- CHANGES.rst
- README.rst
- html5lib/html5parser.py
- html5lib/inputstream.py
- html5lib/tests/test_encoding.py
- html5lib/tests/test_stream.py
- html5lib/tokenizer.py
Also redo our API per #120 to distinguish encodings from different sources.
> Update encoding detection

- CHANGES.rst
- html5lib/__init__.py
- html5lib/html5parser.py
- html5lib/tests/test_parser2.py
I seem to have managed to screw up and end up with the treebuilders getting reverse document order! This fixes it so it gets document order *and* duplicate attribute behaviour correct. Also push a release to fix this.
> Fix attribute order

- requirements-install.sh
- requirements-test.txt
- requirements.txt
- setup.py
Prior to setuptools 20.10.0 there is patchy support for environment markers,
and setup.py fails while parsing them.
html5lib requires at least setuptools 18.5 for its environment markers.
However, @gsnedders developed a way to monkey patch pkg_resources
so that it always uses _markerlib, which allows all environment markers
to be used for any version of setuptools.  Some patching of _markerlib
is also required so that it works on Python 3 also.
On removing the dependency for setuptools>=18.5, pip partially fails on
Python 2.6 with an error `Double requirement given: ordereddict`
and does not install the requirements.txt.
Fixed by removing ordereddict from requirements-test.txt
> Monkeypatch pkg_resources to always use _markerlib

- .travis.yml
Travis CI automatically updates submodules during initialisation.
> Remove redundant submodule update

- .travis.yml
- requirements-install.sh
- requirements.txt
- setup.py
This project uses a syntax for importing urllib.parse from six which was introduced in Six version 1.4
The import can be found [here](https://github.com/html5lib/html5lib-python/blob/master/html5lib/filters/sanitizer.py#L6)
The relevant change in Six can be found [here](https://bitbucket.org/gutworth/six/commits/1f2c7f5d14be9027d180aa00138a1d29c8f48a6f?at=1.4.0#Lsix.pyT188)
This can cause an issue if a project has a previous version of Six (say version 1.3) installed when installing html5lib
EDIT:
importing `viewkeys` in html5parser.py requires six 1.9
> Declare implicit dependency on Six 1.9 or higher

- html5lib/filters/sanitizer.py
errors on invalid escape sequences in strings, such as "\s"
i.e. anything not mentioned in https://docs.python.org/3/reference/lexical_analysis.html#strings
> make compatible with python 3.6

- html5lib/filters/alphabeticalattributes.py
- html5lib/tests/test_alphabeticalattributes.py
If a tag has an attribute with a None namespace and one with a str namespace,
then this filter would fail with a TypeError in Python 3. This fixes that.
Fixes #322
> Fix alphabeticalattributes filter namepsace problem

- tox.ini
This fixes tox.ini so that you can pass arguments to py.test.
For example:
```
tox -e py34-base html5lib/tests/test_serializer.py
```
will now only run the serializer tests.
```
tox -e py34-base -- -vv
```
will run with super verbose mode and tons of data will go flying by in your
terminal.
> Fix tox.ini to allow specifying pytest tests

- requirements-install.sh
Avoid passing `-U` to `pip install` commands. It causes the six package to upgrade, which fails on the Travis 3.4 image. I cannot reproduce this locally, so I'm left to conclude that the Travis Python 3.4 image is corrupt in some way. The installed six package is perfectly fine for testing, so use it without upgrading. All builds now pass.
Install six package first to avoid upgrading it then downgrading it in some test configurations.
> Fix Travis CI builds on Python 3.4

- AUTHORS.rst
- CHANGES.rst
- html5lib/constants.py
- html5lib/tests/serializer-testdata/options.test
this addresses #194 
i added some test data, but it's a bit irrelevant as the tests already test for irrelevant.
great pun there, right?  right? right!
> added `itemscope` as a boolean attribute (issue #194)

- .travis.yml
- README.rst
- html5lib/_trie/_base.py
- html5lib/filters/alphabeticalattributes.py
- html5lib/html5parser.py
- html5lib/tests/test_alphabeticalattributes.py
- html5lib/treewalkers/etree.py
- requirements.txt
- setup.py
- tox.ini
> Drop support for Python 2.6

- .appveyor.yml
- tox.ini
This is the first subset of https://github.com/html5lib/html5lib-python/pull/293 .
> Add AppVeyor testing

- html5lib/tests/conftest.py
Fixes #329 
If you run pytest without pytest-expect or u-msgpack-python, then it'll show something like this:
```
$ pytest
======================================================= test session starts ========================================================
platform linux2 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/willkg/mozilla/html5lib-python, inifile: pytest.ini
******************************************************************************
ERROR: Either pytest-expect or its dependency u-msgpack-python is not
installed. Please install them both before running pytest.
******************************************************************************
collected 0 items / 1 errors …
```
> Fail hard with tracebacks if pytest-expect isn't working

- html5lib/_utils.py
- html5lib/html5parser.py
Python 2.6 support was recently dropped in https://github.com/html5lib/html5lib-python/pull/356.
Here's a bit more old code that can be removed.
> Remove redundant <=2.6 code

- .appveyor.yml
The Python 3.5 and 3.6 builds pass without problems.
> .appveyor.yml: Add Python 3.5 and 3.6 environments

- .appveyor.yml
The AppVeyor build running all tox environments in
a single job takes a long time to report any status,
and the log is difficult to load.
> Split AppVeyor build into 10 jobs

- html5lib/constants.py
This adds docstrings to the exceptions in the constants module for #307.
> Document exceptions in constants module

- .appveyor.yml
- .travis.yml
- requirements-test.txt
- tox.ini
This also removes dependence on `./requirements-install.sh` and `flake8-run.sh`
> Re-enable codecov

- html5lib/tests/README
This nixes the last bit about nose re: issue #182.
> Remove last note about nose

- html5lib/_inputstream.py
- html5lib/constants.py
- html5lib/html5parser.py
ReparseException is used internally and not intended for external use.
Fixes #371
> Make ReparseException private

- html5lib/_inputstream.py
Le this: https://github.com/html5lib/html5lib-python/issues/347
> Regexp change for future compatibility. Fixes #347

- html5lib/treeadapters/__init__.py
- html5lib/treeadapters/genshi.py
- html5lib/treeadapters/sax.py
This adds docs for html5lib.treeadapters for issue #307.
> First pass at docs for html5lib.treeadapters

- html5lib/treebuilders/__init__.py
- html5lib/treebuilders/base.py
- html5lib/treebuilders/etree_lxml.py
This covers `html5lib.treebuilders` docs for issue #307.
> First pass at treebuilder docs

- html5lib/serializer.py
This documents the `html5lib.serializer` module for issue #307.
> First pass at documenting serializer

- doc/html5lib.filters.rst
- doc/html5lib.rst
- doc/html5lib.treeadapters.rst
- doc/html5lib.treebuilders.rst
- doc/html5lib.treewalkers.rst
- html5lib/html5parser.py
- html5lib/treewalkers/__init__.py
This fixes some issues in building documentation in general and adjusts the autodoc settings to generate docs for the supported public API.
This improves the documentation of the html5parser module.
Are there other things in the html5parser module that should be part of the public API? Are there better examples to include?
> html5parser documentation pass

- html5lib/filters/alphabeticalattributes.py
- html5lib/filters/inject_meta_charset.py
- html5lib/filters/lint.py
- html5lib/filters/optionaltags.py
- html5lib/filters/sanitizer.py
- html5lib/filters/whitespace.py
This covers `html5lib.filters` in issue #307.
Is this documentation for filters clear enough for a 1.0?
> First pass at documenting html5lib.filters

- html5lib/treewalkers/__init__.py
- html5lib/treewalkers/base.py
This covers the html5lib.treewalker item in issue #307.
> Document html5lib.treewalkers

- html5lib/_inputstream.py
- html5lib/serializer.py
- html5lib/tests/serializer-testdata/core.test
- setup.py
> Misc. source comment typos

- .appveyor.yml
It looks like this was missed in #358. It is causing build failures in #395 and #396.
> Remove Appveyor Python 3.3 builds

- html5lib/_inputstream.py
The `bytes` type is available on all support Pythons. On Python 2 it is an alias of `str` (same as six). Reduce unnecessary compatibility shims and by using modern Python idioms. Makes the code more forward compatible with Python 3.
> Remove unnecessary use of six.binary_type

- html5lib/_inputstream.py
`io.BytesIO` is available on all supported Pythons. Can simplify by assuming the import will succeed.
> Remove unnecessary compatibility shim for BytesIO

- html5lib/_trie/_base.py
- html5lib/treebuilders/dom.py
Note that collections.abc has been added in Python 3.3.
Fixes #402
> Try to import Mapping and MutableMapping from collections.abc

- tox.ini
Modern flake8 has a good default for exclude that includes the tox
directory.
https://gitlab.com/pycqa/flake8/blob/2b333fad1abe0bdb2e04132eabb0822e6ce63888/src/flake8/defaults.py#L4-14
> Remove unnecessary flake8 exclude

- html5lib/_ihatexml.py
This can be helpful in finding the code triggering the warning.
> Improve the 'Coercing non-XML name' warning.

- html5lib/_inputstream.py
- html5lib/constants.py
- html5lib/html5parser.py
- html5lib/tests/test_serializer.py
- html5lib/tests/tokenizer.py
- html5lib/treebuilders/base.py
- utils/entities.py
Available since Python 2.7. Instances discovered using pyupgrade.
> Use modern Python syntax set literals and dict comprehension

- html5lib/tests/test_stream.py
According to pytest docs:
```
marks in pytest.mark.parametrize
Removed in version 4.0.
Applying marks to values of a pytest.mark.parametrize call is now deprecated.
...
This was considered hard to read and understand, and also its implementation
presented problems to the code preventing further internal improvements in the
marks architecture.
To update the code, use pytest.param
```
> Fix Pytest4.x compatibility error

- parse.py
https://docs.python.org/3/library/optparse.html
> Deprecated since version 3.2: The optparse module is deprecated and
> will not be developed further; development will continue with the
> argparse module.
> Replace deprecated optparse with argparse

- .appveyor.yml
- .travis.yml
- setup.py
- tox.ini
Python 3.7 was released on June 27, 2018.
https://docs.python.org/3/whatsnew/3.7.html
Use 'dist: xenial' in Travis to allow using Python version 3.7. Travis
officially added support for Xenial on 2018-11-08.
https://blog.travis-ci.com/2018-11-08-xenial-release
> Add testing and document support for Python 3.7 & PyPy3

- README.rst
Suggestion to fix https://github.com/html5lib/html5lib-python/issues/439.
Also update list of supported versions, EOL 3.4 was dropped in https://github.com/html5lib/html5lib-python/pull/421 (and pypa/pip@2c1010e dropped support for 3.4 in pip, shipped in 19.2).
> Document Python support

- html5lib/_inputstream.py
Previously, this code tried to match everything with strings
beginning with "<"; now we jump forward to each "<" and compare
there. This also alters the jumpTo implementation to avoid
computing a (perhaps long) slice, making repeated calls O(n^2).
> Make scanning for meta encoding much quicker

- .pytest.expect
- .travis.yml
- html5lib/treebuilders/etree_lxml.py
Fixes #488. Note that this still needs tests.
> Fix #488: append document-child comments in document order in lxml

- html5lib/_utils.py
This just directly imports the first commit from https://github.com/pypa/pip/pull/8278. Fixes #494. This doesn't fill me with joy, but I guess sometimes we do the perhaps silly thing for pip.
(@tiran this is just your commit, let me know if you have any objection to it landing here)
> Don't use cElementTree on Python 3

- CHANGES.rst
- html5lib/filters/sanitizer.py
- html5lib/tests/sanitizer.py
- html5lib/tests/test_sanitizer.py
> Deprecate the sanitizer and recommend Bleach

- .appveyor.yml
- .travis.yml
- tox.ini
> Stop running coverage on Travis/AppVeyor

- html5lib/tests/conftest.py
- html5lib/tests/sanitizer.py
- html5lib/tests/tokenizer.py
- html5lib/tests/tree_construction.py
- requirements-test.txt
Add a wrapper not to break pytest 4 (needed for Python 2 support).
============================= test session starts ==============================
platform linux -- Python 3.9.0b5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /builddir/build/BUILD/html5lib-1.1, configfile: pytest.ini
plugins: expect-1.1.0
collected 0 items / 1 error
==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.9/site-packages/pluggy/manager.py:84: …
> Use Node.from_parent() constructor to support pytest 6

- html5lib/_inputstream.py
- html5lib/serializer.py
- html5lib/tests/test_serializer.py
- html5lib/treebuilders/etree.py
- html5lib/treewalkers/etree.py
- requirements-test.txt
The Python 3.7 CI job [has started failing](https://github.com/html5lib/html5lib-python/actions/runs/3206548648/jobs/5240435219):
```
self._load_entrypoint_plugins()
File "/home/runner/work/html5lib-python/html5lib-python/.tox/py/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
ERROR: InvocationError for command /home/runner/work/html5lib-python/html5lib-python/.tox/py/bin/flake8 . (exited with code 1)
```
This is because importlib_metadata 5.0 removes some deprecations, and it's a dependency of Flake8. But new Flake8 works, so let's update:
* https://github.com/python/importlib_metadata/issues/406
* …
> Bump Flake8 to fix CI for Python 3.7

- .appveyor.yml
- .github/workflows/python-tox.yml
- .travis.yml
- CHANGES.rst
- README.rst
- setup.py
- tox.ini
Closes https://github.com/html5lib/html5lib-python/issues/537.
Python 3.9 was released on 2020-10-05.
Python 3.10 was released on 2021-10-04.
Python 3.11 was released on 2022-10-24.
Let's test them and declare support.
> Add support for Python 3.9 and 3.10 and 3.11

- html5lib/tests/test_sanitizer.py
- pytest.ini
Fixes https://github.com/html5lib/html5lib-python/issues/529.
Fixes `PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.`
Also don't show own `DeprecationWarning` when testing own code.
```console
$ tox -e py38
GLOB sdist-make: /private/tmp/html5lib-python/setup.py
py38 inst-nodeps: /private/tmp/html5lib-python/.tox/.tmp/package/1/html5lib-1.2.dev0.zip
py38 installed: attrs==21.4.0,coverage==5.5,distlib==0.3.4,filelock==3.6.0,flake8==3.8.4,html5lib @ file:///private/tmp/html5lib-python/.tox/.tmp/package/1/html5lib-1.2.dev0.zip,iniconfig==1.1.1,mccabe==0.6.1,mock==4.0.3,packaging==21.3,platformdirs==2.5.1,pluggy==1.0.0,py==1.11.0,pycodestyle==2.6.0,pyflakes==2.2.0,pyparsing==3.0.7,pytest==6.2.5,pytest-expect==1.1.0,six==1.16.0,toml==0.10.2,tox==3.24.5, …
```
> Fix pytest warnings

- README.rst
Fixes https://github.com/html5lib/html5lib-python/issues/535.
Alternatively, we could just remove mention of the mailing list. And is the IRC channel still active?
> README: Replace broken mailing list link with archive

- html5lib/_ihatexml.py
refactoring code with For Else which is more pythonic, concise and efficient; how do you think this change which has practical value？
> Use for:else: where it makes sense

- html5lib/constants.py
While I believe we could just remove `command` and `event-source` (as I commented on the issue), it's safer just to leave them be for now and revisit this for "2.0".
To not lose track of the fact that those two elements are out of place, this PR just documents their removals. More importantly, it sorts the elements so it's easier to compare them with sources of truth:
- https://html.spec.whatwg.org/#void-elements; and the more wordy
- https://developer.mozilla.org/en-US/docs/Glossary/Void_element
Fixes #203
> Sort void elements alphabetically, document ones that don't match current standard

- html5lib/tests/test_meta.py
- requirements-test.txt
Starting python 3.3, this is in the stdlib.
Fixes #541
> tests: drop dependency on external mock module for newer python
